services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  jupyter:
    image: jupyter/pyspark-notebook:python-3.11
    ports:
      - "8888:8888"
      - "4050:4050"
    environment:
      JUPYTER_TOKEN: password
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - minio
