[project]
name = "jupyter-yt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyterlab>=4.4.9",
    "boto3>=1.34.0",
    "minio>=7.2.0",
    "faker>=20.0.0",
    "pandas>=2.0.0",
    "pyarrow>=10.0.0",
]
